#项目端口
server:
  port: 9000

#应用名称
spring:
  application:
    name: zuul-server

# 网关配置/sector/card/studentId

#配置Eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #ip:port
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    consumer-8005:
      strip-prefix: false
      path: /sector/**
      serviceId: consumer-8005
